import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img />
          <a href="">Home</a>
          <a href="/events">Events</a>
          <a href="about-us">About</a>
        </nav>
      </header>
      <main className={styles.main}>
        {data.map((ev,index)=>(
          <a key={index} href={`/events/${ev.id}`}>
            <Image src={ev.image} alt={ev.title} width={200} height={200} />
            <h2>{ev.title}</h2>
            <p>{ev.description}</p>
          </a>
        ))}
      </main>
    </>
  );
}

export const getServerSideProps = async () =>{
  const {events_categories} = await import('../data/data.json');
  console.log(events_categories);
  return {
    props : {data : events_categories}
  }
}
